[package]
name = "git-srep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
git_utils_shared = { path = "../git_utils_shared"}
colored = "2.0.0"